# Generated by Django 5.0.4 on 2024-05-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_name',
            old_name='name',
            new_name='p_name',
        ),
    ]
