# Generated by Django 5.0.4 on 2024-05-02 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_rename_name_product_name_p_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=True)),
                ('image', models.ImageField(upload_to='admin_module/images')),
                ('model', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admin_module.product_name')),
            ],
        ),
    ]
