# Generated by Django 5.0.4 on 2024-05-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_product_manager_productmst_productsubcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_manager',
            old_name='admin_id',
            new_name='manager_id',
        ),
    ]
