# Generated by Django 3.2.5 on 2025-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20),
        ),
    ]
